name: Python CI/CD

on:
  push:
    branches:
      - main  # change to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest  # or your testing command

      # - name: Build and deploy
      #   run: |
      #     python3 src/index.py
      #     # Your deployment commands (e.g., to deploy to a server or a cloud platform)
